### ISSUE TITLE
Sample Issue

### ISSUE THREAD

**Issue by eawhite** [dhoehna/LoYoT#1]
Description of Issue:
This is a description of what's going on. Keep the description brief and specific

Reproduction steps:
1. Do this thing
2. Do this other thing
3. Do this final thing
4. The issue happens

Relevant images:
![image](https://cloud.githubusercontent.com/assets/12287664/7715691/ea00bda2-fe3e-11e4-8c79-a6490936b764.png)

**Comment by dhoehna** [comment]
If you are using windows, you can use the snipping tool to easily capture an image.  Please use this tool instead of print screen.  I mean, you can use print screen, then pain, or some other image manipulation software to crop the photo so we see only the relevant information.

But...you know.  You can just use the one step snipping tool.

**Comment by eawhite** [comment]
Umm I'm gonna say that you can take a screenshot in whatever way is easiest to you : P

**Comment by dhoehna** [comment]
Yes, you can do that.  I have just found the snipping tool to be much easier.  

But, my first comment wasn't meant to be derogatory.

**Comment by eawhite** [comment]
oh no worries, I was just trying to poke fun : )
