### ISSUE TITLE
Update Front Facing Web Interface documentation

### ISSUE THREAD

**Issue by eawhite** [dhoehna/LoYoT#2]
Feel free to rename this section. Remember to keep it short, and focus on what's changed from the LCA.

**Comment by nkotev** [comment]
The design of the LOYOT has gone through some changes from the original idea we had in the LCA documentation. The preliminary idea was to have 3 layers of buttons that would allow the user to navigate the subjects he/she was interested in. When selecting one subject the other subject buttons would fade out and be hidden. Then pressing a submit button would give back the links to the subjects the user chose. This design was good, but it was a bit too complex because a lot of buttons were appearing initially, and the algorithm for hiding them appropriately was complex, and was properly functioning for two layers of buttons not tree that we had. Thus our design changed slightly by making a menu with the tree main subjects Math, English, CS, and when the user clicks on a specific tab, radio buttons show up with specific classes that can be checked ex: Statistics, Calculus. Then the submit button can be clicked for the user to get the links to the specific classes they are interested in. This way the design is simpler and yet it looks better put together and more complex than before.  In this scenario we also don’t need to write a more complex hiding links function, because the 3 main subjects are separated in different tabs.
